### PR TITLE
Migrated to track 2 datalake SDK

### PR DESCRIPTION
**Pull request by gapra-msft**

### CODE REVIEW

**Comment by gapra-msft** [comment]
These alerts are from files I added to keep supporting logging without pipeline.LogLevel. Should be safe to just dismiss the alerts. Thoughts?

**Review by tasherif-msft — APPROVED** [review]
ah thats nice to see :')

**Review by nakulkar-msft — APPROVED** [review]
should merge to dev instead

**Comment by gapra-msft** [comment]
> should merge to dev instead

Good catch

**Review by siminsavani-msft — APPROVED** [review]

**Pull request merged**
