### PR TITLE
Update include-directory-stub inline help

### PR DESCRIPTION
**Pull request by schoag-msft**
Update include-directory-stub inline help to match public docs

### CODE REVIEW

**Review by gapra-msft — APPROVED** [review]

**Comment by seanmcc-msft** [comment]
@siminsavani-msft please take a look.

**Review by siminsavani-msft — APPROVED** [review]
lgtm! feel free to ignore the codespell for this pr!

**Comment by gapra-msft** [comment]
@schoag-msft actually I just realized this is against the main branch, could you make your PR off the dev branch and make that the target of this PR?

**Comment by schoag-msft** [comment]
Ack. Closing and will let you know the new one.

**Pull request closed without merging**
