### PR TITLE
fix: s/syncOverwriteResaonNewerLMT/syncOverwriteReasonNewerLMT/g

### PR DESCRIPTION
**Pull request by chenrui333**
relates to https://github.com/Homebrew/homebrew-core/pull/146964

### CODE REVIEW

**Comment by chenrui333** [comment]
> @chenrui333 Could you please change the base branch to dev. We generally merge into the dev branch for new changes.

yeah, totally.

**Comment by chenrui333** [comment]
(sounds like you folks should update the repo's default branch to dev as well?)

**Comment by chenrui333** [comment]
done!

**Comment by vivshin-genesys** [comment]
Any movements with this? 

There is an obvious typo in 
[[cmd/syncComparator.go](https://github.com/Azure/azure-storage-azcopy/pull/2393/files#diff-9076bf04dfb4c754eb5b40394e23b03cbe2f7eafd384c44dbcbe864cd862935d)](https://github.com/Azure/azure-storage-azcopy/blob/main/cmd/syncComparator.go)

**Comment by gapra-msft** [comment]
Hi @chenrui333, it looks like this is already resolved in the dev branch. This will be released as part of our next release cycle. Thanks! Feel free to close this PR after confirming the same. 
https://github.com/Azure/azure-storage-azcopy/blob/d1824f070afc941913c0842a49863a7f9f0b43f1/cmd/syncComparator.go#L197

**Comment by gapra-msft** [comment]
This is now fixed in main. Closing this PR as a result.

**Pull request closed without merging**
