### PR TITLE
[bug] Fix SIGSERV on macOS Monterey, fixes #1790

### LINKED ISSUE #1790: Segmentation violation when running azcopy on mac os ( via brew)
##### Note: The version is visible when running AzCopy without any argument
10.15.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac OS Monterey with latest updates
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy

### What problem was encountered?

➜  ~ azcopy
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ff80957b4f6]

runtime stack:
runtime.throw({0x4ad6f85?, 0xffffffffffffffff?})
	runtime/panic.go:992 +0x71
runtime.sigpanic()
	runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4898360, 0xc000133a68)
	runtime/cgocall.go:157 +0x5c fp=0xc000133a40 sp=0xc000133a08 pc=0x4006cdc
github.com/mattn/go-ieproxy._Cfunc_CFNumberGetValue(0x0, 0x9, 0xc00003c348)
	_cgo_gotypes.go:194 +0x49 fp=0xc000133a68 sp=0xc000133a40 pc=0x42c4b89
github.com/mattn/go-ieproxy.cfNumberGetGoInt.func1(0x42c4f49?, 0x4898400?)
	github.com/mattn/go-ieproxy@v0.0.3/ieproxy_darwin.go:43 +0x59 fp=0xc000133aa8 sp=0xc000133a68 pc=0x42c5599
github.com/mattn/go-ieproxy.cfNumberGetGoInt(0x0?)
	github.com/mattn/go-ieproxy@v0.0.3/ieproxy_darwin.go:43 +0x37 fp=0xc000133ad8 sp=0xc000133aa8 pc=0x42c5517
github.com/mattn/go-ieproxy.writeConf()
	github.com/mattn/go-ieproxy@v0.0.3/ieproxy_darwin.go:76 +0x26c fp=0xc000133bc8 sp=0xc000133ad8 pc=0x42c5a0c
sync.(*Once).doSlow(0x1?, 0x7?)
	sync/once.go:68 +0xc2 fp=0xc000133c28 sp=0xc000133bc8 pc=0x407f462
sync.(*Once).Do(...)
	sync/once.go:59
github.com/mattn/go-ieproxy.getConf(...)
	github.com/mattn/go-ieproxy@v0.0.3/ieproxy_darwin.go:23
github.com/mattn/go-ieproxy.GetConf(...)
	github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:36
github.com/mattn/go-ieproxy.proxyMiddleman()
	github.com/mattn/go-ieproxy@v0.0.3/proxy_middleman_darwin.go:12 +0x57 fp=0xc000133cc8 sp=0xc000133c28 pc=0x42c4437
github.com/mattn/go-ieproxy.GetProxyFunc(...)
	github.com/mattn/go-ieproxy@v0.0.3/proxy_middleman.go:10
github.com/Azure/azure-pipeline-go/pipeline.newDefaultHTTPClient()
	github.com/Azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:208 +0x1d fp=0xc000133d00 sp=0xc000133cc8 pc=0x42c88fd
github.com/Azure/azure-pipeline-go/pipeline.init()
	github.com/Azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:202 +0x19 fp=0xc000133d20 sp=0xc000133d00 pc=0x42caa79
runtime.doInit(0x5219160)
	runtime/proc.go:6222 +0x126 fp=0xc000133e50 sp=0xc000133d20 pc=0x4046fc6
runtime.doInit(0x5217d20)
	runtime/proc.go:6199 +0x71 fp=0xc000133f80 sp=0xc000133e50 pc=0x4046f11
runtime.main()
	runtime/proc.go:233 +0x1d3 fp=0xc000133fe0 sp=0xc000133f80 pc=0x4039ff3
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc000133fe8 sp=0xc000133fe0 pc=0x4069261

### How can we reproduce the problem in the simplest way?
brew install azcopy
~ azcopy

### Have you found a mitigation/solution?
no
I think that because of this error my storage explorer also is not working and I really use it every day:-(

### PR DESCRIPTION
**Pull request by rkettelerij**
Fixes SIGSERV segmentation violation error caused by [go-ieproxy](github.com/mattn/go-ieproxy) dependency. This is fixed in https://github.com/mattn/go-ieproxy/issues/35. Upgrading to a more recent version of the mentioned dependency fixes the issue.

Fixes #1790

### CODE REVIEW

**Comment by rkettelerij** [comment]
@microsoft-github-policy-service agree

**Comment by nakulkar-msft** [comment]
Thanks you for the contribution!

**Comment by rkettelerij** [comment]
Can this be reviewed?

**Comment by nakulkar-msft** [comment]
Hi @rkettelerij, can you rebase your change off dev branch? We do not submit directly to master.

**Comment by rkettelerij** [comment]
Hi @nakulkar-msft maybe I misunderstand but haven't you already done so? See change 6 days ago.

**Comment by nakulkar-msft** [comment]
> Hi @nakulkar-msft maybe I misunderstand but haven't you already done so? See change 6 days ago.

Hi rkettelerij, Sorry for responding late. I have to figure something out here. Master has a different change than dev, and we do not want that to be merged in dev at this point. It would be helpful if you could rebase your branch against dev.

**Pull request closed without merging**
