### PR TITLE
Hot fix 10.2.1: Correct missed error check in oauthTokenManager

### LINKED ISSUE #481: AzCopy 10.2.0 segfault on service principal login in Linux
Trying to login with service principal in linux using azcopy 10.2.0 results in a segfault. Running
```
env AZCOPY_SPA_CLIENT_SECRET=<secret> ./azcopy login --service-principal --application-id <id>
```
with <secret> the service principal secret and application-id the client id results in a segfault with the following trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45bbe4]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/common.(*UserOAuthTokenManager).SecretLogin(...)
        /home/vsts/work/1/s/common/oauthTokenManager.go:210 +0xfd
github.com/Azure/azure-storage-azcopy/cmd.loginCmdArgs.process(...)
        /home/vsts/work/1/s/cmd/login.go:173 +0x214
github.com/Azure/azure-storage-azcopy/cmd.init.8.func2(...)
        /home/vsts/work/1/s/cmd/login.go:52 +0x293
github.com/spf13/cobra.(*Command).execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(...)
        /home/vsts/work/1/s/cmd/root.go:85 +0x88
main.main()
        /home/vsts/work/1/s/main.go:60 +0x211
```

I've tried this both from an Ubuntu 18.04 Azure VM and my local Gentoo laptop, with the same results.

### PR DESCRIPTION
**Pull request by adreed-msft**
Self-explanatory.

Such a simple thing to miss.

Fixes #481.

### CODE REVIEW

**Comment by JohnRusk** [comment]
> Maybe we should add a linter to our build?
> The IDE had a warning for the dereferencing.

Yes. Good idea. Interestingly, I'm not seeing the warning in my copy of the IDE. Can you send me a screenshot of yours?  (With the old code)

**Comment by zezha-msft** [comment]
@JohnRusk sure, here it is:

image

**Comment by JohnRusk** [comment]
Weird, it doesn't do that for me.  I can't figure out what setting I might be missing....

**Comment by zezha-msft** [comment]
@JohnRusk maybe you could upgrade your IDE? And make sure you haven't disabled the inspections:

image

**Comment by zezha-msft** [comment]
Improved error message:

```
INFO: (NOTICE FOR SETTING ENVIRONMENT VARIABLES: Bear in mind that setting an environment variable from the command line will be readable in your command line history. For variables that contain credentials, consider clearing these entries from your history or using a small script of sorts to prompt for and set these variables.)

Failed to perform login command:
adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.
Trace ID: 1858cf47-153c-4ab7-853e-e7ca2faa0500
Correlation ID: 69a58e26-5803-4596-9c38-998ca1292042
Timestamp: 2019-07-03 23:06:23Z","error_codes":[7000215],"timestamp":"2019-07-03 23:06:23Z","trace_id":"1858cf47-153c-4ab7-853e-e7ca2faa0500","correlation_id":"69a58e26-5803-4596-9c38-998ca1292042"}

NOTE: If your credential was created in the last 5 minutes, please wait a few minutes and try again.
```

**Pull request merged**
