### PR TITLE
Enable support for preserving SMB info on Linux.

### PR DESCRIPTION
**Pull request by linuxsmiths**
Implemented the GetSDDL/PutSDDL GetSMBProperties/PutSMBProperties
methods for Linux using extended attributes.
Following are the xattrs we use for fetching/setting various required
info.

// Extended Attribute (xattr) keys for fetching various information from Linux cifs client.
const (
        CIFS_XATTR_CREATETIME     = "user.cifs.creationtime" // File creation time.
        CIFS_XATTR_ATTRIB         = "user.cifs.dosattrib"    // FileAttributes.
        CIFS_XATTR_CIFS_ACL       = "system.cifs_acl"        // DACL only.
        CIFS_XATTR_CIFS_NTSD      = "system.cifs_ntsd"       // Owner, Group, DACL.
        CIFS_XATTR_CIFS_NTSD_FULL = "system.cifs_ntsd_full"  // Owner, Group, DACL, SACL.
)

Majority of the changes are in sddl/sddlHelper_linux.go which implement
the following Win32 APIs for dealing with SIDs.

	ConvertSecurityDescriptorToStringSecurityDescriptorW
	ConvertStringSecurityDescriptorToSecurityDescriptorW
	ConvertSidToStringSidW
	ConvertStringSidToSidW

Note: I have skipped Object ACE support in sddl/sddlHelper_linux.go as
      those should not be used for filesystem properties, only AD object
      properties.
      Can someone confirm this?

TBD:
Conditional SID

### CODE REVIEW

**Review by adreed-msft — APPROVED** [review]

**Comment by shalinijoshi19** [comment]
@linuxsmiths are you able to help resurrect this branch with the latest and greatest and put this up for PR afresh? Thanks

**Comment by linuxsmiths** [comment]
> @linuxsmiths are you able to help resurrect this branch with the latest and greatest and put this up for PR afresh? Thanks

yeah, sure.

**Comment by linuxsmiths** [comment]
> > @linuxsmiths are you able to help resurrect this branch with the latest and greatest and put this up for PR afresh? Thanks
> 
> yeah, sure.

done and refreshed

**Comment by linuxsmiths** [comment]
Accidentally closed.

**Review by nakulkar-msft — APPROVED** [review]

**Pull request merged**
