### PR TITLE
Added trivy file

### PR DESCRIPTION
**Pull request by gapra-msft**

### CODE REVIEW

**Review by vibhansa-msft — APPROVED** [review]

**Comment by adreed-msft** [comment]
Would Github's Dependabot not work as well?
https://docs.github.com/en/code-security/dependabot/working-with-dependabot

**Comment by gapra-msft** [comment]
> Would Github's Dependabot not work as well? https://docs.github.com/en/code-security/dependabot/working-with-dependabot

I can look into this. We just happen to use trivy in Blobfuse so I just integrated that here.

**Comment by adreed-msft** [comment]
> I can look into this. We just happen to use trivy in Blobfuse so I just integrated that here.

Gotcha, gotcha.

**Comment by gapra-msft** [comment]
> > I can look into this. We just happen to use trivy in Blobfuse so I just integrated that here.
> 
> Gotcha, gotcha.

I'll follow this PR up with another one with dependabot since it seems to have some cool features like creating PRs for you.

**Pull request merged**
