### PR TITLE
Update golang version

### PR DESCRIPTION
**Pull request by nakulkar-msft**

### CODE REVIEW

**Review by zezha-msft — APPROVED** [review]

**Comment by zezha-msft** [comment]
Is there a big feature or something we need in 1.19?

**Comment by nakulkar-msft** [comment]
> Is there a big feature or something we need in 1.19?

We've 3 issues like 1912.

**Review by adreed-msft — APPROVED** [review]

**Review by siminsavani-msft — APPROVED** [review]

**Comment by gapra-msft** [comment]
Could you please link any associated GH issues so they get auto-closed with the merge of this PR?

**Comment by gapra-msft** [comment]
Related Issue: https://github.com/Azure/azure-storage-azcopy/issues/1905

**Pull request merged**
