### PR TITLE
typo

### PR DESCRIPTION
**Pull request by andrescodas**

### CODE REVIEW

**Comment by gapra-msft** [comment]
Hi @andrescodas could you please make a PR against the dev branch? We don't normally accept PRs into main.

**Comment by andrescodas** [comment]
> Hi @andrescodas could you please make a PR against the dev branch? We don't normally accept PRs into main.

Here it is #2133

**Comment by gapra-msft** [comment]
> > Hi @andrescodas could you please make a PR against the dev branch? We don't normally accept PRs into main.
> 
> Here it is #2133

you may have to recreate a different branch off of dev. PR #2133 has many other changes.

**Comment by andrescodas** [comment]
Hi. It seems already fixed on dev https://github.com/andrescodas/azure-storage-azcopy/commit/fec0318192d751bf0c249c97e7278a7f44fd8fce

If dont, please proceed to fix it without my commit.   Thanks!

**Comment by gapra-msft** [comment]
> Hi. It seems already fixed on dev [fec0318](https://github.com/Azure/azure-storage-azcopy/commit/fec0318192d751bf0c249c97e7278a7f44fd8fce)
> 
> If dont, please proceed to fix it without my commit. Thanks!

Great! I'll go ahead and close these then! This does seem to be fixed in dev already.

**Pull request closed without merging**
