### PR TITLE
Converted numbers to strings in JSON output

### PR DESCRIPTION
**Pull request by zezha-msft**
JS is a funny language. 🤣

### CODE REVIEW

**Comment by adreed-msft** [comment]
```
[] == 0
0 == "0"
"0" == []
```

Try running those lines in a js console 👀

**Comment by zezha-msft** [comment]
I need to update our smoke tests which depend on the JSON output.

**Comment by adreed-msft** [comment]
Good catch!

**Comment by adreed-msft** [comment]
Is there anything else that might rely upon this json output?

**Comment by zezha-msft** [comment]
@adreed-msft yes, I think the other partner teams will have to make some changes when we release. So we have to call this out as a breaking change.

**Pull request merged**
