### PR TITLE
Updating docs for copy and sync commands

### PR DESCRIPTION
**Pull request by normesta**
Including Gen2 in the list of supported sources and destinations for both copy and sync commands

### CODE REVIEW

**Review by gapra-msft — APPROVED** [review]

**Comment by normesta** [comment]
Yikes. Didn't realize that I had this PR still open so I accidentally made another commit to it. Would any previous reviewers, mind reviewing the additional delta here? Thanks!

**Comment by gapra-msft** [comment]
@normesta lgtm!

**Comment by normesta** [comment]
THanks @gapra-msft . Curious about the process here. Do we sign off on our own contributions, or is there a designated admin o your team that signs off on these? I'm not sure if your repo uses the same "# sign-off" semantics. Thx!

**Comment by gapra-msft** [comment]
@normesta you should be good since you have 2 sign offs on this PR. Please merge this PR at your convenience.

**Comment by normesta** [comment]
Ok Thank you @gapra-msft !

#sign-off

**Comment by normesta** [comment]
#sign-off

**Comment by normesta** [comment]
Hmm. The "# sign-off" semantic indeed does not work the same here. @gapra-msft can you please advise me as to how I can merge this PR? I see no option in the UI of this issue that I can use to do that. I attempted to use the sign-off hash tag that we use in the docs.microsoft collection and that doesn't appear to kick off any sort of merge automation.

**Comment by gapra-msft** [comment]
Oh interesting, it might be that you don't have merge permissions on this repo. I can manually merge this for you if that's alright? @normesta

**Comment by normesta** [comment]
Yes, please do merge for me. Thank you! I don't believe I have permission to do that myself. That's probably a good thing :-)

**Comment by Daiannec** [comment]
Hello team, I still have the permission error.

This is a test account .. I am trying to import the PST file and I am using a SAS key ( M365 Purview Portal)

2023/12/07 18:53:44 ==> REQUEST/RESPONSE (Try=1/4.086ms, OpTime=4.086ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://c57d47f6c9e44a79acccc01.blob.core.windows.net/ingestiondata/PST%2Fbackup12.pst?se=2024-01-06T18%3A33%3A56Z&si=IngestionSasForAzCopy202311271809445768&sig=-REDACTED-&sr=c&sv=2015-04-05
   Accept: application/xml
   User-Agent: AzCopy/10.22.0 azsdk-go-service.Client/v1.2.0 (go1.19.12; Windows_NT)
   X-Ms-Client-Request-Id: 98fbfec3-aaeb-40d4-4980-6139b5e1b9d2
   x-ms-version: 2023-08-03
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Date: Thu, 07 Dec 2023 18:53:44 GMT
   Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
   Vary: Origin
   X-Ms-Client-Request-Id: 98fbfec3-aaeb-40d4-4980-6139b5e1b9d2
   X-Ms-Error-Code: AuthorizationPermissionMismatch
   X-Ms-Request-Id: 71562e67-f01e-005e-223e-298721000000
   X-Ms-Version: 2023-08-03
Response Details: 

2023/12/07 18:53:44 INFO: [P#0-T#1] UPLOADSUCCESSFUL: https://c57d47f6c9e44a79acccc01.blob.core.windows.net/ingestiondata/PST/backup12.pst
2023/12/07 18:53:44 JobID=c214f6c3-dcc7-4049-5e7e-36af557d17d3, Part#=0, TransfersDone=3 of 3
2023/12/07 18:53:44 all parts of entire Job c214f6c3-dcc7-4049-5e7e-36af557d17d3 successfully completed, cancelled or paused
2023/12/07 18:53:44 is part of Job which 1 total number of parts done 
2023/12/07 18:53:44 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs: 32
2023/12/07 18:53:44 100.0 %, 3 Done, 0 Failed, 0 Pending, 0 Skipped, 3 Total, 2-sec Throughput (Mb/s): 459.7148
2023/12/07 18:53:44 
[c214f6c3-dcc7-4049-5e7e-36af557d17d3.log](https://github.com/Azure/azure-storage-azcopy/files/13604092/c214f6c3-dcc7-4049-5e7e-36af557d17d3.log)


I appreciate any tip.

**Comment by Daiannec** [comment]
[c214f6c3-dcc7-4049-5e7e-36af557d17d3.log](https://github.com/Azure/azure-storage-azcopy/files/13604156/c214f6c3-dcc7-4049-5e7e-36af557d17d3.log)

Hello team, 
I still have error 403 ... someone can help me? 
This is test account

2023/12/07 18:53:44 ==> REQUEST/RESPONSE (Try=1/41.5623ms, OpTime=41.5623ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://c57d47f6c9e44a79acccc01.blob.core.windows.net/ingestiondata/PST%2Fazcopy.exe?se=2024-01-06T18%3A33%3A56Z&si=IngestionSasForAzCopy202311271809445768&sig=-REDACTED-&sr=c&sv=2015-04-05
   Accept: application/xml
   User-Agent: AzCopy/10.22.0 azsdk-go-service.Client/v1.2.0 (go1.19.12; Windows_NT)
   X-Ms-Client-Request-Id: a7d25825-3d5f-48ff-59ab-d6c8a5e518fc
   x-ms-version: 2023-08-03
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Date: Thu, 07 Dec 2023 18:53:43 GMT
   Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
   Vary: Origin
   X-Ms-Client-Request-Id: a7d25825-3d5f-48ff-59ab-d6c8a5e518fc
   X-Ms-Error-Code: AuthorizationPermissionMismatch
   X-Ms-Request-Id: 14eff5e5-301e-006e-043e-2939ee000000
   X-Ms-Version: 2023-08-03

**Comment by Daiannec** [comment]
Thank you.. I opened.

=)

Daianne C Pinheiro
Identity Support Engineer
Working Hours: Mon-Fri 08:00-17:00 (EST|GMT-5)
Need help outside of my working hours?
Technical Advisor: Alison Hudson, ***@***.******@***.***>
Manager: Juan Albert Armada, ***@***.******@***.***>
***@***.***

**Pull request merged**
