### PR TITLE
Create SAS tokens for blob->* transfers on the fly in the STE

### PR DESCRIPTION
**Pull request by adreed-msft**
Pasted from the old PR:

Some background:

Previous iterations of this PR have done this creation in the frontend. This would cause problems if a user attempted to resume a transfer of this style, because the SAS has to come in externally in that scenario. Furthermore, this would have caused issues with S2S transfers, as S2S transfers may potentially contain multiple source containers, and UDKs can only create SAS tokens for containers or blobs, not the entire service.

Therefore, I moved it all to the STE. It lives under a single-instance struct named UserDelegationAuthenticationManager, which does two things:

If a UDK was created, it maps container names to SAS tokens.
If a UDK was not created, it creates empty SAS tokens.
Furthermore, rather than just grabbing the URL once from SIP, we grab it every time we make a call to enable refreshing the underlying UDK and user delegated SAS token

### CODE REVIEW

**Comment by zezha-msft** [comment]
@adreed-msft tests need some fixing.

**Comment by mohsha-msft** [comment]
Please fix the conflicts and failing UTs.

**Comment by doanduyhai** [comment]
Any update ?

**Comment by zezha-msft** [comment]
Closing for now as the service has a new feature that makes this scenario a lot easier.

**Comment by seanralexander** [comment]
> Closing for now as the service has a new feature that makes this scenario a lot easier.

What feature is this which makes it easier?

**Comment by karimdabbagh** [comment]
> Hi @seanralexander, the new feature allows us to pass an additional bearer token that the destination account can pass to the source account, thus eliminating the need to generate user delegation SAS which requires more permission.
> 
> We'll adopt this feature soon.

any updates on this?

**Pull request closed without merging**
