### PR TITLE
Un-hide list-of-files flag for copy command

### PR DESCRIPTION
**Pull request by zezha-msft**

### CODE REVIEW

**Comment by JohnRusk** [comment]
Removed from 10.4, pending perf tuning

**Comment by zezha-msft** [comment]
@JohnRusk do we need to benchmark this? Is there some kind of numbers we have to hit?

**Comment by JohnRusk** [comment]
@zezha-msft There are two concerns here:
1. Is it fast enough to expose?  I think it is for lists of hundreds of files, but not for lists of thousands. (It was super slow when I tested with 3000 some time ago).
2. If we fix the perf, will that entail a breaking change to the existing --list-of-files?  (I suspect it probably will).  If it will, that becomes a strong reason to _not_ make the current implementation public.

**Comment by zezha-msft** [comment]
Closing for now, not ready to expose this flag.

**Pull request closed without merging**
