### PR TITLE
fixing small typo (,) in help of jobs clean

### PR DESCRIPTION
**Pull request by mstenz**
easy and small change. just found it.

### CODE REVIEW

**Review by nakulkar-msft — APPROVED** [review]

**Comment by nakulkar-msft** [comment]
Change the base branch to dev

**Review by adreed-msft — APPROVED** [review]
Needs rebase to dev

**Comment by mstenz** [comment]
@adreed-msft  sorry, just have seen your command. I do not know how to rebase.

**Comment by adreed-msft** [comment]
Don't worry about it. I gotcha.

**Pull request merged**
